spring:
  application:
    name: test-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: test_user
    password: test_user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/root-changelog.xml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /test-service
  port: 8080

